version: '3.8'

services:
   mysql_8:
     image: mysql:8
     container_name: mysql_8
     volumes:
       - /e/mysql_8/data:/var/lib/mysql
       - /e/mysql_8/run:/var/run/mysqld
       - /e/mysql_8/init_scripts/:/docker-entrypoint-initdb.d/
     restart: always
     environment:
       MYSQL_ROOT_USER: root
       # TODO: change the password
       MYSQL_ROOT_PASSWORD: Qwer4321
       MYSQL_PS1: "mysql_8> "
       TZ: Europe/Helsinki
     ports:
       - 13306:3306
