version: '3.8'

services:
   mysql_multi_8_0:
     image: mysql:8.0
     container_name: mysql_multi_8_0
     volumes:
       - ./mysql_multi_8_0/data:/var/lib/mysql
       - ./mysql_multi_8_0/run:/var/run/mysqld
       - ./mysql_multi_8_0/init_scripts/:/docker-entrypoint-initdb.d/
     restart: always
     environment:
       MYSQL_ROOT_USER: root
       # TODO: change the password
       MYSQL_ROOT_PASSWORD: Qwer4321
       MYSQL_PS1: "mysql_multi_8_0> "
       TZ: Europe/Helsinki
     ports:
       - 13306:3306

   mysql_multi_5_7:
     image: mysql:5.7
     container_name: mysql_multi_5_7
     volumes:
       - ./mysql_multi_5_7/data:/var/lib/mysql
       - ./mysql_multi_5_7/run:/var/run/mysqld
       - ./mysql_multi_5_7/init_scripts/:/docker-entrypoint-initdb.d/
     restart: always
     environment:
       MYSQL_ROOT_USER: root
       # TODO: change the password
       MYSQL_ROOT_PASSWORD: Asdf0987
       MYSQL_PS1: "mysql_multi_5_7> "
       TZ: Europe/Helsinki
     ports:
       - 23306:3306
