version: '3.8'

services:
  mariadb_latest:
    image: mariadb:latest
    container_name: mariadb_container
    environment:
      MYSQL_ROOT_PASSWORD: Qwer4321
      LANG: C.UTF-8
      TZ: Europe/Helsinki
    ports:
      - 23306:3306
    volumes:
      - /e/mariadb/data:/var/lib/mysql
      - /e/mariadb/run:/var/run/mysqld
      - /e/mariadb/init_scripts/:/docker-entrypoint-initdb.d/
      - /e/mariadb/custom:/opt/custom
      - ./my_utf8mb4.cnf:/etc/mysql/conf.d/my_utf8mb4.cnf
